model:
  name: transformer
  args:
    src_vocab_size: 8000
    tgt_vocab_size: 8000
    encoder_layers: 4
    decoder_layers: 2
    model_dim: 256
    attn_head: 8
    ffn_dim: 512
    dropout: 0.1

optimizer:
  name: adam
  args:
    betas:
      - 0.9
      - 0.98
    eps: 1e-9
    weight_decay: 0.0005


scheduler:  # note this is not implemented yet
  name: inverse-sqrt 
  args:
    warmup: 1000

schema:
  fields:
    - sequence
    - sequence
  vocabs:
    - data/vocab.joint.8k.model
    - data/vocab.joint.8k.model
  shared_vocabs: true

trainer:
  data:
    - data/train.kan
    - data/train.eng
  batch_size: 8
  epochs: 25
  max_length: &max_length
    - 512
    - 512
  max_length_crop: true
  fp16: true
  chunk_size: 4
  loader_threads: 1
  log_frequency: 25u
  log_first: 10

  criterion:
    name: kl_divergence
    args:
      num_labels : 8000
      label_smooth_rate: 0.1


validator:
  frequency: 500
  data:
    - data/dev.kan
    - data/dev.eng
  batch_size: 8
  criteria:
    - name: cross_entropy
      args:
        label_smooth_rate: 0.0

checkpoint:
  frequency: 250
  keep: 10




