model:
  name: transformer_lm
  args:
    vocab_size: 8000
    layers: 6
    model_dim: 512
    attn_heads: 8
    ffn_dim: 2048
    dropout: 0.1

optimizer:
  name: adam
  args:
    betas:
      - 0.9
      - 0.98
    eps: 1e-9
    weight_decay: 0.0005

scheduler:
  name: noam
  args:
    warmup_steps: 2000
    model_dim: 512
    constant: 1

schema:
  fields:
    - sequence
    #- sequence
  vocabs:
    - data/eng-deu/vocab.joint.8k.model
    #- data/eng-deu/vocab.joint.8k.model
  shared_vocabs: true

trainer:
  data:
    #- data/eng-deu/train.deu
    - data/eng-deu/train.eng
  mini_batch: 10
  maxi_batch: 1000
  epochs: 100000
  max_length: &max_length
    - 512
    #- 512
  max_length_crop: true
  fp16: true
  chunk_size: 8
  loader_threads: 2
  log_frequency: 50u
  #log_frequency: 1u
  log_first: 5

  criterion:
    name: kl_divergence
    args:
      num_labels : 8000
      label_smooth_rate: 0.1

validator:
  frequency: 500
  data:
    #- data/eng-deu/dev.deu
    - data/eng-deu/dev.eng
  batch_size: 8
  criteria:
    - name: cross_entropy
      args:
        label_smooth_rate: 0.0

checkpoint:
  frequency: 100000
  keep: 10
